In [3]:
#1d Array
import numpy as np
my_list=[1,2,3,4,5,6,7,8,9,0]
arr=np.array(my_list)

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [11]:
#2d Array
my_mat=[[1,2,3],[3,4,5],[7,8,9]]
mat=np.array(my_mat)
print(mat)

[[1 2 3]
 [3 4 5]
 [7 8 9]]


In [16]:
#Generating arrays using numpy inpuilt function
#in a range
np.arange(0,100,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

In [20]:
#All zeros
print(np.zeros((2,4)))
print(np.zeros(9))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [25]:
#All Ones
print(np.ones(3))
print(np.ones((2,4)))

[1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [27]:
#Evenly spaced points The output is 1d array
print(np.linspace(10,20,4))

[10.         13.33333333 16.66666667 20.        ]


In [29]:
#Identity Matrix
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [30]:
#Arrays of random numbers

In [33]:
#Random numbers from uniform distribution
print(np.random.rand(5))
print(np.random.rand(5,3))

[0.46503988 0.11684205 0.71249595 0.39667105 0.32493855]
[[0.00209858 0.88809127 0.03128824]
 [0.15413762 0.14494448 0.0329074 ]
 [0.86005173 0.91299499 0.44160446]
 [0.29432791 0.44653568 0.4368973 ]
 [0.04172666 0.32010358 0.05869411]]


In [36]:
#Random numbers from Standard normal distribution
print(np.random.randn(4))
print(np.random.randn(4,6))

[-0.33760227  0.63820371 -0.10081592 -0.21344498]
[[ 0.00494589  0.93339274 -0.36427768  1.44941863  0.34621859  0.2925473 ]
 [-0.72254708  0.90649242  0.6976867   1.55273324  0.2122825  -0.15255605]
 [ 1.37834007 -0.03714835 -0.35096645 -2.47428264 -0.36556132  0.54990832]
 [-1.19970043  0.49835453 -0.54057096 -0.60225145  0.19023549  1.03324284]]


In [41]:
#Random number from a range i.e max and min given lowest inclusive and highest exclussive
print(np.random.randint(1,100,6))

[65 88 90 72 78 35]


In [43]:
#Array Functions

In [50]:
arr=np.arange(25)
ranarr=np.random.randint(0,50,10)

In [62]:
arr=arr.reshape(5,5) #Reshaping an array can be done but the number of elements must be the same

In [65]:
print(ranarr.max())
print(ranarr.min())
print(ranarr.argmax())
print(ranarr.argmin())
print(arr.shape)

49
8
9
5
(5, 5)


In [67]:
arr.dtype

dtype('int64')