In [2]:
import numpy as np

In [4]:
arr=np.arange(0,11)

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
print(arr[8])
print(arr[3:])
print(arr[:5])
print(arr[5:8])

8
[ 3  4  5  6  7  8  9 10]
[0 1 2 3 4]
[5 6 7]


In [12]:
arr[:5]=101
arr

array([101, 101, 101, 101, 101,   5,   6,   7,   8,   9,  10])

In [14]:
slice_array=arr[:7]

In [16]:
slice_array

array([101, 101, 101, 101, 101,   5,   6])

In [18]:
slice_array[:]=109

In [20]:
slice_array

array([109, 109, 109, 109, 109, 109, 109])

In [22]:
#Any changes to the slices from an array is also reflected on the original array
#because the slice provides an view for the array (more like reference)
arr

array([109, 109, 109, 109, 109, 109, 109,   7,   8,   9,  10])

In [24]:
#To avoid the ablove issue we need to use the following copy function
arr_copy=arr.copy()

In [26]:
arr_copy

array([109, 109, 109, 109, 109, 109, 109,   7,   8,   9,  10])

In [30]:
arr_copy[3:]=-10
print(arr_copy)
print(arr)
#Original array remains unaffected 

[109 109 109 -10 -10 -10 -10 -10 -10 -10 -10]
[109 109 109 109 109 109 109   7   8   9  10]


In [31]:
#Indexing in 2d Array

In [34]:
arr=np.array([[5,3,2],[1,2,3],[5,87,4]])
arr

array([[ 5,  3,  2],
       [ 1,  2,  3],
       [ 5, 87,  4]])

In [39]:
print(arr[0][0])
print(arr[0])
print(arr[1,1])

5
[5 3 2]
2


In [43]:
#Grabing slices of 2D array
print(arr[1:,:])

[[ 1  2  3]
 [ 5 87  4]]


In [51]:
arr=np.arange(1,11)
#Get a subset of an array based on conditions
bool_arr=arr%3==0
#bool_arr contains a array with true and false values for each of the elements according to the condition
print(bool_arr)
print(arr[bool_arr])

[False False  True False False  True False False  True False]
[3 6 9]
